export const ALERT_THRESHOLDS = {
  UV_INDEX_DANGER: 8,
  WIND_GUSTS_KMH_DANGER: 60, // km/h
  PRECIPITATION_DAILY_MM_DANGER: 20, // mm
  TEMP_MAX_C_DANGER: 35, // °C
  TEMP_MIN_C_DANGER: -10, // °C
};
